### ISSUE TITLE
Task list for the mini world description into a schema design

### ISSUE THREAD

**Issue by olivedae** [rprotasov/edsger#2]
I decided having an issue instead of markdown file would be more helpful since it's not hidden in a folder and won't require additional commits to make changes/updates as we progress:

**Users**
- [x] Supports non-account users
- [x] Users (w/ account) consist of personal information such as:
  - [x] First and last name
  - [x] Email address (Primary Key)
  - [x] Password digest
  - [x] Email confirmed
  - [x] Icon
  - [x] Date joined
  - [x] Date last accessed 
- [x] Previous searches for users are saved
- [x] Users (w/ account) can star/favourite routes
- [x] Users (w/ account) can organise routes into boxes
- [ ] Integrations of users (w/ account) preferred choice of map application (I.E. Google, Apple)
- [ ] Users (w/ account) can save locations with meaningful names for quick access (I.E. their home address given the name 'Casa') which they can use in place of addresses (I.E. in searches)
- [ ] Users can search for routes given various specifications
- [ ] Users (w/ account) can share a route/box with 0 or more other people, in addition user the route was shared with may or may not have an account
- [ ] Users (w/ account) can be notified after a specific amount of inactivity with a box/route that they will no longer be notified of updates and changes with the route(s). Users will be notified with an email that notifications are being suppressed after it will not remove them from watching it. Once they visit the app again that route will be unsuppressed
- [x] Shared boxes/routes may have editable permissions for users
  - [x] View/Edit

**Boxes**
- [x] Boxes consist of the information:
  - [x] Name
  - [x] Icon
  - [x] Date created
  - [x] Owner of the box
- [x] Keeps track of the last visited and update times by other users
- [x] Allows users to place routes and move routes around in the box and with other boxes
- [ ] Updates for routes

**Routes**
- [x] Routes consist of the information:
  - [x] The box it belongs to
  - [x] The name
  - [x] Date created
  - [x] Date last updated
  - [x] Locations contained in the route
  - [x] Owner
- [ ] Routes can be configured to notify a user when an update occurs in the route
- [x] Once a user stars a route, it will automatically be watched
- [x] A route can consist of one or multiple locations specified by the user
- [ ] Derived values include the total length, estimated time for travel, and the remaining time left (if they are to have started on the route)
- [ ] Routes (such as those with multiple locations) consist of sub-routes knowns as walks that join location A to location B. Thus, routes are derived from walks.

**Route/Walk Cache**

To be used more as an internal mechanism for Hooked, however some constraints are below
- [ ] A walk cannot connect to itself (I.E. location A location B are the same)

**Comment by ericvoorhis** [comment]
Latest model put together in https://github.com/rprotasov/hooked/commit/d46f61a0ca8e9a0d80824894fc6837fd6d3c398f:
- User table finished
- Box table mostly finished
- Route table started

**Comment by ericvoorhis** [comment]
Finished User and Box, Added to Route, and made a new Location table in https://github.com/rprotasov/hooked/pull/3/commits/fac10154ee5cf41b6697305e463e6b66994678cf. Next I can complete "Locations contained in the route" under the "Routes" task list section by setting up the 1 to n relation between Route and Location.

**Comment by olivedae** [comment]
See comments in 6af9e59
